### ISSUE TITLE
count causing resources to be outputted as tuples? 

### ISSUE THREAD

**Issue by sblack4** [nlarzon/terraform-azure-vnet#2]
When using the output I got this error: 
```
Error: Unsupported attribute

  on main.tf line 72, in resource "azurerm_virtual_network_peering" "spoke_to_hub":
  72:   resource_group_name       = module.vnet.resource_group.name
    |----------------
    | module.vnet.resource_group is tuple with 1 element

This value does not have any attributes.
```

When I change my reference to the variable it seems to go away:
```
  resource_group_name       = module.vnet.resource_group[0].name
```

--- 
I think it is because of the use of count on [line 7 of main.tf](https://github.com/rhythmictech/terraform-azure-vnet/blob/9acdcf0ddd5b33081032bc225b66e1fe44a58b96/main.tf#L7). I've gotta get this fixed pronto but I'll submit a PR once I've got it 😃

**Comment by nlarzon** [comment]
thanks
